import { Component, ViewEncapsulation } from '@angular/core';
import { NavbarComponent } from '../navbar/navbar.component';
import { NavBarConfig } from '../navbar/navbar-modal';
import { WrapperInterface } from '../modals';
import { CardListComponentComponent } from '../card-for-list-component/card-for-list-component';
import {
  CardConfig,
  CardGridConfig,
} from '../card-collection-component/card.modal';
import { SectionWrapperComponent } from '../shared/section-wrapper/section-wrapper.component';
import { CardComponentComponent } from '../card-collection-component/card-collection-component';
import { GridViewComponent } from '../grid-view/grid-view.component';

@Component({
  selector: 'app-microservices',
  standalone: true,
  imports: [
    NavbarComponent,
    CardListComponentComponent,
    SectionWrapperComponent,
    GridViewComponent,
  ],
  templateUrl: './microservices.component.html',
  styleUrl: './microservices.component.css',
})
export class MicroservicesComponent {
  navbarConfig: NavBarConfig = {
    isBorderTop: false,
    isBorderBottom: true,

    style: {
      maxWidth: '1280px',
      position: 'fixed',
      padding: '12px 40px',
      top: '55px',
      left: '50%',
      transform: 'translateX(-50%)',
      borderRadius: '80px',
      borderBottomColor: '#15A46E',
      zIndex: '999',
    },
    logo: {
      url: './microServices_logo.png',
      position: 'left',
    },
    buttons: [
      {
        position: 'center',
        alignWithLogo: true,
        buttonsGroup: [
          {
            id: 'home',
            text: 'Home',
            // icon: 'home',
            // showIcon: true,
            // iconPosition: 'right',
            shape: 'rectangle',
            corners: 'rounded',
            foregroundColor: '#333333',
            backgroundColor: '#800080',
            transparent: true,
            hasBorder: false,
            shadow: false,
            navigate: true,
            url: '/',
          },
          {
            id: 'aboutus',
            text: 'About Us',
            // icon: 'info',
            // showIcon: true,
            // iconPosition: 'left',
            shape: 'rectangle',
            corners: 'rounded',
            foregroundColor: '#333333',
            backgroundColor: 'var(--primary-color)',
            transparent: true,
            hasBorder: false,
            shadow: false,
            navigate: true,
            url: '/about',
          },
          {
            id: 'services',
            text: 'Services',
            // icon: 'info',
            // showIcon: true,
            // iconPosition: 'left',
            shape: 'rectangle',
            corners: 'rounded',
            foregroundColor: '#333333',
            backgroundColor: 'var(--primary-color)',
            transparent: true,
            hasBorder: false,
            shadow: false,
            navigate: true,
            url: '/services',
          },
          {
            id: 'case-studies',
            text: 'Case Studies',
            // icon: 'info',
            // showIcon: true,
            // iconPosition: 'left',
            shape: 'rectangle',
            corners: 'rounded',
            foregroundColor: '#333333',
            backgroundColor: 'var(--primary-color)',
            transparent: true,
            hasBorder: false,
            shadow: false,
            navigate: true,
            url: '/case-studies',
          },
          {
            id: 'contact-us',
            text: 'Contact Us',
            shape: 'rectangle',
            corners: 'rounded',
            foregroundColor: '#333333',
            backgroundColor: '#800080',
            transparent: true,
            hasBorder: false,
            shadow: false,
            navigate: true,
            url: '/contact',
          },

          {
            id: 'schedule-a-call',
            text: 'Schedule A Call',
            icon: 'wifi_calling',
            showIcon: true,
            iconPosition: 'right',
            shape: 'rectangle',
            corners: 'rounded',
            foregroundColor: '#DD8208',
            transparent: true,
            hasBorder: true,
            borderColor: '#DD8208',
            shadow: false,
            navigate: true,
            url: '/call',
            isPillButton: true,
            // onClick: (event: Event) => this.handleClick(event),
          },
        ],
      },
    ],
  };

  heroBannerConfig: CardConfig = {
    imageAlignment: 'right',
    sectionWidths: [50, 50],
    customStyles: {
      backgroundColor: 'transparent',
      padding: '0px',
      alignItems: 'center',
      display: 'flex',
    },
    header: {
      headerStyles: {
        display: 'flex',
        flexDirection: 'column',
        // rowGap: '20px',
      },
      title:
        'Scalable Microservices for <span color="#9D6F00">Startups & Businesses</span> ',
      titleTag: 'h1',
      titleStyles: {
        color: 'black',
        fontSize: '48px',
        fontWeight: '800',
        letterSpacing: '0px',
        width: '98%',
      },
      titleAlign: 'left',

      description:
        'Future-proof your applications with enterprise-grade | microservices designed for speed, security, and scale.',
      descriptionTag: 'p',
      descriptionStyles: {
        color: '#131313',
        fontSize: '18px',
        fontWeight: '400',
        width: '71%',
        marginBottom: '40px',
      },
      descriptionAlign: 'left',

      buttonsAlign: 'left',
      buttons: [
        {
          text: 'Get a Free Consultation',
          hasBorder: false,
          isPillButton: true,
          backgroundColor: '#15A46E',
          customStyles: {
            padding: '16px 24px',
          },
        },
        {
          text: 'See My Work',
          hasBorder: false,
          isPillButton: true,
          backgroundColor: '#DD8208',
          customStyles: {
            padding: '16px 24px',
          },
        },
      ],
    },
    image: {
      position: 'top-half',
      src: './hero_image.png',
      title: '',
      description: '',
      hoverEffect: false,
    },
  };

  cardGridConfig: CardGridConfig = {
    gridTitle: 'What We Do',
    gridTitleTag: 'h2',
    gridTitleStyles: {
      color: '#171921',
      'font-size': '42px',
      'font-weight': '400',
      'text-align': 'center',
    },
    layoutType: 'grid',
    gridSubtitle:
      'You have problems with leaking pipes, broken tiles, lost keys or want to tidy up the trees around you, of course you need our help!',
    gridSubtitleTag: 'p',
    gridSubtitleStyles: {
      color: '#666',
      'font-size': '18px',
      'text-align': 'center',
      'font-weight': '400',
    },
    cardConfigs: [
      {
        // layout: 'list',
        // width: 100,
        // iframeUrl: 'https://www.example.com',
        // iframeWidth: '100%',
        // iframeHeight: '400px',
        imageAlignment: 'left', // or 'right'
        sectionWidths: [30, 70], // Image takes 40%, content takes 60%
        cardActions: [
          { icon: 'schedule', text: '1 day ago' },
          { icon: 'comment', text: '3 COMMENTS' },
          { icon: 'favorite', text: '1 LIKE' },
        ],
        // header: {
        //   title: 'It is a long established fact that a reader',
        //   // align: 'center',
        //   buttonsAlign: 'left',
        //   buttons: [
        //     { text: 'Edit', align: 'left', icon: '✏️', hasBorder: false },
        //     { text: 'Delete', align: 'right', icon: '✏️', hasBorder: false },
        //   ],
        // },
        image: {
          position: 'top-half',
          src: 'https://media.istockphoto.com/id/1934523700/photo/close-up-on-man-hand-using-mobile-phone.jpg?s=1024x1024&w=is&k=20&c=8rb1PLOQMgOY52356fBOBjWfVknpGT-uxfeJk_h3ols=',
          title: 'Title on Image',
          description: 'This is a description shown on hover.',
          hoverEffect: false,
        },
        content: {
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
          // customHtml: '<p>Custom HTML content here</p>',
          // details: {
          //   align: 'multi-column',
          //   columns: 2,
          //   rows: 2,
          //   content: [
          //     [
          //       { text: 'Detail 1', icon: '🔍' },
          //       { text: 'Detail 2', icon: '📅' },
          //     ],
          //     // [
          //     //   { text: 'Detail 3', icon: '💼' },
          //     //   { text: 'Detail 4', icon: '🌍' },
          //     // ],
          //   ],
          // },
        },
        body: {
          type: 'text',
          // align: 'center',
          content: `It is a long established fact that a reader`,
          // buttons: [{ text: 'More Info', align: 'center' }],
        },
        footer: {
          type: 'buttons',
          align: 'left',
          text: 'This is a dynamically aligned footer text',
          buttons: [
            {
              text: 'Edit',
              align: 'right',
              group: 'right',
              icon: 'edit',
              showIcon: true,
              iconPosition: 'left',
              shape: 'square',
              corners: 'rounded',
              foregroundColor: '#ffffff',
              backgroundColor: '#576675',
              hasBorder: false,
              shadow: true,
              transparent: false,
            },
            {
              text: 'Done',
              align: 'right',
              group: 'right',
              icon: 'check_circle',
              showIcon: true,
              iconPosition: 'left',
              shape: 'square',
              corners: 'rounded',
              foregroundColor: '#ffffff',
              backgroundColor: '#008000',
              hasBorder: false,
              shadow: true,
              transparent: false,
            },
            {
              text: 'Delete',
              align: 'right',
              group: 'right',
              icon: 'delete',
              showIcon: true,
              iconPosition: 'left',
              shape: 'square',
              corners: 'rounded',
              foregroundColor: '#ffffff',
              backgroundColor: '#DF0404',
              hasBorder: false,
              shadow: true,
              transparent: false,
            },
          ],
        },
      },
      {
        // layout: 'list', //Use the list layout
        // width: 100,
        cardActions: [
          { icon: 'schedule', text: '1 day ago' },
          { icon: 'comment', text: '3 COMMENTS' },
          { icon: 'favorite', text: '1 LIKE' },
        ],
        // header: {
        //   title: 'Chihuahua 2',
        //   // align: 'center',
        //   buttonsAlign: 'left',
        //   buttons: [
        //     { text: 'Edit', align: 'left', icon: '✏️', hasBorder: false },
        //     { text: 'Delete', align: 'right', icon: '✏️', hasBorder: false },
        //   ],
        // },
        image: {
          position: 'top-half',
          src: 'https://media.istockphoto.com/id/1934523700/photo/close-up-on-man-hand-using-mobile-phone.jpg?s=1024x1024&w=is&k=20&c=8rb1PLOQMgOY52356fBOBjWfVknpGT-uxfeJk_h3ols=',
          title: 'Title on Image',
          description: 'This is a description shown on hover.',
          hoverEffect: false,
        },
        content: {
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
          // customHtml: '<p>Custom HTML content here</p>',
          // details: {
          //   align: 'multi-column',
          //   columns: 2,
          //   rows: 2,
          //   content: [
          //     [
          //       { text: 'Detail 1', icon: '🔍' },
          //       { text: 'Detail 2', icon: '📅' },
          //     ],
          //     // [
          //     //   { text: 'Detail 3', icon: '💼' },
          //     //   { text: 'Detail 4', icon: '🌍' },
          //     // ],
          //   ],
          // },
        },
        body: {
          type: 'text',
          align: 'left',
          content: `It is a long established fact that a reader`,
          buttons: [{ text: 'More Info', align: 'center', hasBorder: false }],
        },
        footer: {
          type: 'buttons',
          align: 'left',
          text: 'This is a dynamically aligned footer text',
          buttons: [
            {
              text: 'Edit',
              align: 'left',
              group: 'left',
              icon: 'edit',
              showIcon: true,
              iconPosition: 'left',
              shape: 'square',
              corners: 'rounded',
              foregroundColor: '#ffffff',
              backgroundColor: '#576675',
              hasBorder: false,
              shadow: true,
              transparent: false,
            },
            {
              text: 'Done',
              align: 'left',
              group: 'left',
              icon: 'check_circle',
              showIcon: true,
              iconPosition: 'left',
              shape: 'square',
              corners: 'rounded',
              foregroundColor: '#ffffff',
              backgroundColor: '#008000',
              hasBorder: false,
              shadow: true,
              transparent: false,
            },
            {
              text: 'Delete',
              align: 'left',
              group: 'left',
              icon: 'delete',
              showIcon: true,
              iconPosition: 'left',
              shape: 'square',
              corners: 'rounded',
              foregroundColor: '#ffffff',
              backgroundColor: '#DF0404',
              hasBorder: false,
              shadow: true,
              transparent: false,
            },
          ],
        },
      },
      {
        // layout: 'list', //Use the list layout
        // width: 100,
        cardActions: [
          { icon: 'schedule', text: '1 day ago' },
          { icon: 'comment', text: '3 COMMENTS' },
          { icon: 'favorite', text: '1 LIKE' },
        ],
        // header: {
        //   title: 'Chihuahua 2',
        //   // align: 'center',
        //   buttonsAlign: 'left',
        //   buttons: [
        //     { text: 'Edit', align: 'left', icon: '✏️', hasBorder: false },
        //     { text: 'Delete', align: 'right', icon: '✏️', hasBorder: false },
        //   ],
        // },
        image: {
          position: 'top-half',
          src: 'https://media.istockphoto.com/id/1934523700/photo/close-up-on-man-hand-using-mobile-phone.jpg?s=1024x1024&w=is&k=20&c=8rb1PLOQMgOY52356fBOBjWfVknpGT-uxfeJk_h3ols=',
          title: 'Title on Image',
          description: 'This is a description shown on hover.',
          hoverEffect: false,
        },
        content: {
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
          // customHtml: '<p>Custom HTML content here</p>',
          // details: {
          //   align: 'multi-column',
          //   columns: 2,
          //   rows: 2,
          //   content: [
          //     [
          //       { text: 'Detail 1', icon: '🔍' },
          //       { text: 'Detail 2', icon: '📅' },
          //     ],
          //     // [
          //     //   { text: 'Detail 3', icon: '💼' },
          //     //   { text: 'Detail 4', icon: '🌍' },
          //     // ],
          //   ],
          // },
        },
        body: {
          type: 'text',
          align: 'left',
          content: `It is a long established fact that a reader.`,
          buttons: [{ text: 'More Info', align: 'center', hasBorder: false }],
        },
        footer: {
          type: 'buttons',
          align: 'left',
          text: 'This is a dynamically aligned footer text',
          buttons: [
            {
              text: 'Edit',
              align: 'left',
              group: 'left',
              icon: 'edit',
              showIcon: true,
              iconPosition: 'left',
              shape: 'square',
              corners: 'rounded',
              foregroundColor: '#ffffff',
              backgroundColor: '#576675',
              hasBorder: false,
              shadow: true,
              transparent: false,
            },
            {
              text: 'Done',
              align: 'left',
              group: 'left',
              icon: 'check_circle',
              showIcon: true,
              iconPosition: 'left',
              shape: 'square',
              corners: 'rounded',
              foregroundColor: '#ffffff',
              backgroundColor: '#008000',
              hasBorder: false,
              shadow: true,
              transparent: false,
            },
            {
              text: 'Delete',
              align: 'left',
              group: 'left',
              icon: 'delete',
              showIcon: true,
              iconPosition: 'left',
              shape: 'square',
              corners: 'rounded',
              foregroundColor: '#ffffff',
              backgroundColor: '#DF0404',
              hasBorder: false,
              shadow: true,
              transparent: false,
            },
          ],
        },
      },
      {
        // layout: 'list', //Use the list layout
        // width: 100,
        cardActions: [
          { icon: 'schedule', text: '1 day ago' },
          { icon: 'comment', text: '3 COMMENTS' },
          { icon: 'favorite', text: '1 LIKE' },
        ],
        // header: {
        //   title: 'Chihuahua 2',
        //   // align: 'center',
        //   buttonsAlign: 'left',
        //   buttons: [
        //     { text: 'Edit', align: 'left', icon: '✏️', hasBorder: false },
        //     { text: 'Delete', align: 'right', icon: '✏️', hasBorder: false },
        //   ],
        // },
        image: {
          position: 'top-half',
          src: 'https://media.istockphoto.com/id/1934523700/photo/close-up-on-man-hand-using-mobile-phone.jpg?s=1024x1024&w=is&k=20&c=8rb1PLOQMgOY52356fBOBjWfVknpGT-uxfeJk_h3ols=',
          title: 'Title on Image',
          description: 'This is a description shown on hover.',
          hoverEffect: false,
        },
        content: {
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
          //   customHtml: '<p>Custom HTML content here</p>',
          //   details: {
          //     align: 'multi-column',
          //     columns: 2,
          //     rows: 2,
          //     content: [
          //       [
          //         { text: 'Detail 1', icon: '🔍' },
          //         { text: 'Detail 2', icon: '📅' },
          //       ],
          //       [
          //         { text: 'Detail 3', icon: '💼' },
          //         { text: 'Detail 4', icon: '🌍' },
          //       ],
          //     ],
          //   },
        },
        body: {
          type: 'text',
          align: 'left',
          content: `The Chihuahua is a Mexican breed of toy dog.`,
          buttons: [{ text: 'More Info', align: 'center', hasBorder: false }],
        },
        footer: {
          type: 'buttons',
          align: 'left',
          text: 'This is a dynamically aligned footer text',
          buttons: [
            {
              text: 'Edit',
              align: 'left',
              group: 'left',
              icon: 'edit',
              showIcon: true,
              iconPosition: 'left',
              shape: 'square',
              corners: 'rounded',
              foregroundColor: '#ffffff',
              backgroundColor: '#800080',
              hasBorder: false,
              shadow: true,
              transparent: false,
            },
            {
              text: 'Done',
              align: 'left',
              group: 'left',
              icon: 'check_circle',
              showIcon: true,
              iconPosition: 'left',
              shape: 'square',
              corners: 'rounded',
              foregroundColor: '#ffffff',
              backgroundColor: '#800080',
              hasBorder: false,
              shadow: true,
              transparent: false,
            },
            {
              text: 'Delete',
              align: 'left',
              group: 'left',
              icon: 'delete',
              showIcon: true,
              iconPosition: 'left',
              shape: 'square',
              corners: 'rounded',
              foregroundColor: '#ffffff',
              backgroundColor: '#800080',
              hasBorder: false,
              shadow: true,
              transparent: false,
            },
          ],
        },
      },
      {
        // layout: 'list', //Use the list layout
        // width: 100,
        cardActions: [
          { icon: 'schedule', text: '1 day ago' },
          { icon: 'comment', text: '3 COMMENTS' },
          { icon: 'favorite', text: '1 LIKE' },
        ],
        // header: {
        //   title: 'Chihuahua 2',
        //   // align: 'center',
        //   buttonsAlign: 'left',
        //   buttons: [
        //     { text: 'Edit', align: 'left', icon: '✏️', hasBorder: false },
        //     { text: 'Delete', align: 'right', icon: '✏️', hasBorder: false },
        //   ],
        // },
        image: {
          position: 'top-half',
          src: 'https://media.istockphoto.com/id/1934523700/photo/close-up-on-man-hand-using-mobile-phone.jpg?s=1024x1024&w=is&k=20&c=8rb1PLOQMgOY52356fBOBjWfVknpGT-uxfeJk_h3ols=',
          title: 'Title on Image',
          description: 'This is a description shown on hover.',
          hoverEffect: false,
        },
        content: {
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        },
        body: {
          type: 'text',
          align: 'left',
          content: `The Chihuahua is a Mexican breed of toy dog.`,
          buttons: [{ text: 'More Info', align: 'center', hasBorder: false }],
        },
        footer: {
          type: 'buttons',
          align: 'left',
          text: 'This is a dynamically aligned footer text',
          buttons: [
            {
              text: 'Edit',
              align: 'left',
              group: 'left',
              icon: 'edit',
              showIcon: true,
              iconPosition: 'left',
              shape: 'square',
              corners: 'rounded',
              foregroundColor: '#ffffff',
              backgroundColor: '#800080',
              hasBorder: false,
              shadow: true,
              transparent: false,
            },
            {
              text: 'Done',
              align: 'left',
              group: 'left',
              icon: 'check_circle',
              showIcon: true,
              iconPosition: 'left',
              shape: 'square',
              corners: 'rounded',
              foregroundColor: '#ffffff',
              backgroundColor: '#800080',
              hasBorder: false,
              shadow: true,
              transparent: false,
            },
            {
              text: 'Delete',
              align: 'left',
              group: 'left',
              icon: 'delete',
              showIcon: true,
              iconPosition: 'left',
              shape: 'square',
              corners: 'rounded',
              foregroundColor: '#ffffff',
              backgroundColor: '#800080',
              hasBorder: false,
              shadow: true,
              transparent: false,
            },
          ],
        },
      },
    ],
  };
}
